version: "3.4"
services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.61.1
    depends_on:
      - mqtt
      - influxdb
    volumes:
      - /home/<username>/.homeassistant:/config
      - /home/<username>/src/dehydrated:/home/<username>/src/dehydrated
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id/usb-1234_5678-ff00:/dev/serial/by-id/usb-1234_5678-ff00
    privileged: true
    network_mode: host

  # mqtt:
    # image: fstehle/rpi-mosquitto:latest
    # restart: unless-stopped
    # volumes:
      # - /home/<username>/.homeassistant/mqtt/config:/mqtt/config:ro
      # - /home/<username>/.homeassistant/mqtt/data:/mqtt/data
      # - /home/<username>/.homeassistant/mqtt/passwd:/mqtt/passwd
      # - /home/<username>/src/dehydrated/certs:/mqtt/conf/certs
    # ports:
      # - 1883:1883
      # - 8883:8883
      # - 9001:9001

  influxdb:
    image: hypriot/rpi-influxdb
    volumes:
      - /mnt/influxdb:/data
    environment:
      PRE_CREATE_DB: "home-assistant"
    ports:
      - 8086:8086

  grafana:
    image: heziegl/rpi-grafana:3.1.1
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      - /mnt/influxdb/grafana/etc:/etc/grafana
      - /mnt/influxdb/grafana/data:/data
    ports:
      - 3000:3000
